blank_issues_enabled: false
contact_links:
  - name: 安全问题
    url: https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/about-repository-security-advisories
    about: 请不要公开发布可利用的安全问题，改用私密安全报告。
